Feature
Warckut/bee-test pull request #1
Opened 2024-05-17 11:34 UTC by Warckut

my implementation

2024-05-30 15:26 UTC, lamtev178 commented on webpack.config.js
webpack вообще использовать нельзя было

2024-05-30 15:26 UTC, lamtev178 commented on tsconfig.json
ts вообще использовать нельзя было

2024-05-30 15:26 UTC, lamtev178 commented on src/pages/TimePage.ts
> +    result.push(hrs < 10 ? "0" + hrs : hrs);
Вынеси прибавление незначащего нуля в отдельную функцию

2024-05-30 15:26 UTC, lamtev178 commented on src/pages/Four04.ts
gh-pages отрисовывает свою 404, ее нужно явно переопределять, так работать не будет

2024-05-30 15:26 UTC, lamtev178 commented on src/components/ThoughtsForm.ts
??

2024-05-30 15:26 UTC, lamtev178 commented on src/App.ts
> +const routes: Record<string, { linkLabel: string; component: any }> = {
Добавь enum для linkLabel

2024-05-30 15:26 UTC, lamtev178 commented on src/App.ts
> +    if (!routes[this.currentPage]) {
gh-pages имеет свою 404, так работать не будет

2024-05-30 15:26 UTC, lamtev178 commented on src/components/Header/Header.ts
> +      (name: any) =>
Тут будет просто созданный enum в links

2024-05-30 15:26 UTC, lamtev178 commented on src/components/Link.ts
> +  name: "activity" | "map" | "time";
Создай enum

2024-05-30 15:26 UTC, lamtev178 commented on src/App.ts
Почему вообще App, тут по сути Router находится

2024-05-30 15:26 UTC, lamtev178 commented on src/App.ts
При перезагрузке страницы всегда попадаем на 404

2024-06-18 21:41 UTC, tvivls requested changes
нет метки на карте 
https://github.com/web-bee-ru/ru-test-assignments/blob/main/internship/01-base-frontend-stages.md#второй-уровень

2024-06-18 21:41 UTC, tvivls commented on package.json
по-хорошему не использовать вообще никакие библиотеки. 
стек: чистый js, css, html
+bootstrap

2024-06-18 21:41 UTC, tvivls commented on src/components/Header/Header.ts
> +      </div>
разметку вынеси в соответствующие файлы
js отдельно, html отдельно

2024-06-18 21:41 UTC, tvivls commented on src/App.ts
молодец, что знаешь typescript, но давай ты сделаешь проект на js?)

2024-07-01 16:52 UTC, tvivls requested changes
еще я бы попросила немного доделать верстку, а именно 
<img width="435" alt="image" src="https://github.com/Warckut/bee-test/assets/86954004/f626f9dc-1f21-40bf-becb-8c3581336af9">
<img width="277" alt="image" src="https://github.com/Warckut/bee-test/assets/86954004/4b91f702-0b78-4068-89a8-a46c02c7be78">

не обязательно делать какую-то интерактивность, просто правый угол выглядит пустовато

2024-07-01 16:52 UTC, tvivls commented on index.html
> +          style="color: var(--color-black)"
не пиши inline-стили

2024-07-01 16:52 UTC, tvivls commented on index.html
> +          href="#"
убирай
роутинг должен быть без #, используй history api

2024-07-01 16:52 UTC, tvivls commented on index.html
> +    <script src="https://api-maps.yandex.ru/v3/?apikey=986846d7-9dd1-47b1-a98e-eca824f87a2b&lang=ru_RU"></script>
скрипты выноси вниз body

2024-07-01 16:52 UTC, tvivls commented on index.html
> +          <span style="font-weight: 500">User pages<span class="fw-normal ms-1">- Profile</span></span>
Инлайн стили выноси в классы

исправь везде

2024-07-01 16:52 UTC, tvivls commented on src/index.css
> +body {
не пиши стили к тегам
используй классы

2024-07-01 16:52 UTC, tvivls commented on src/index.js
> +    var xhr = new XMLHttpRequest();
используй `let` или `const`
вместо `XMLHttpRequest` лучше использовать `fetch`

2024-07-01 16:52 UTC, tvivls commented on src/pages/activity/index.js
> +  return () => {};
зачем `return () => {};`?

2024-07-01 16:52 UTC, tvivls commented on src/pages/activity/index.html
> +<main class="container mt-3 pb-3">
тут у тебя есть main, на остальных страницах нет
мб вообще его убрать? он все равно внутри div'a, как-то некрасиво кмк

2024-07-01 16:52 UTC, tvivls commented on src/index.js
> +      e.currentTarget.style.backgroundColor = 'var(--color-bg)';
я бы вынесла в отдельную функцию изменение активного таба

2024-07-01 16:52 UTC, tvivls commented on src/pages/map/index.js
> +  const timeout = setTimeout(() => {
зачем setTimeout на карту?) убирай

2024-07-01 16:52 UTC, tvivls commented on src/pages/map/index.js
> +  };А
`А` 
лишнее оставил

2024-07-01 16:52 UTC, tvivls commented on src/pages/map/index.js
> +const marker = () => {
страшно выглядит
если используешь Яндекс карты - посмотри как там ставится метка на карте, не через картинку точно)

там можно красивее все сделать
поставить маркер, надпись, если надо и много всего...

2024-07-01 16:52 UTC, tvivls commented on src/pages/map/index.js
> +            coordinates: [37.623082, 55.75254],
дублируются координаты

2024-07-01 16:52 UTC, tvivls commented on src/pages/time/index.js
> +  const secs = Math.floor(seconds % 60);
лучше нормальные названия использовать, hours, minutes, seconds
это сокращение тебе ничего не дает, только непонятный нейминг

2024-07-01 16:52 UTC, tvivls commented on src/pages/time/index.js
> +  return time < 10 ? '0' + time : time;
можно использовать padStart - метод специально для строк

2024-07-01 16:52 UTC, tvivls commented on src/index.js
> +document.addEventListener('DOMContentLoaded', function () {
я бы вынесла содержимое в отдельную функцию, чтобы убрать вложенность, а сам addEventListener переместила в начало файла

2024-07-01 16:52 UTC, tvivls commented on src/index.js
> +    requestPage('activity')
при обновлении любой из страниц, кидает на главную
если я обновляю страницу карты, хочу оставаться на карте

2024-07-01 16:52 UTC, tvivls commented on src/pages/time/index.js
> +  return () => clearInterval(interval);
при запуске таймера тебе достаточно запускать его отображение 
а когда покидаешь страницу таймера, можно очищать интервал

2024-07-01 16:52 UTC, tvivls commented on src/pages/time/index.js
> +  return result.join(':');
как будто можно подсократить

2024-07-01 16:52 UTC, tvivls commented on src/pages/time/index.html
> +    class="menu d-flex align-items-center mt-3 px-4 p-3 active"
добавь нижний отступ, режет глаз)
<img width="245" alt="image" src="https://github.com/Warckut/bee-test/assets/86954004/3735a4f3-6ede-45a3-91e7-cf1fb0afe019">

2024-07-01 17:00 UTC, tvivls commented
и еще коммиты пиши как `feat(сущность): описание`
feat: добавление нового функционала
fix: исправление ошибок
pr: исправление комментариев на Pull Request'е

2024-07-03 07:42 UTC, Warckut commented on src/pages/activity/index.js
> +  return () => {};
функция init возвращала функцию, в которой была логика для очистки интервалов и прочего (типа unMount), а так как в разделе activity такой логики нет, то поэтому эта функция здесь пустая, но это уже исправлено

2024-07-04 17:04 UTC, Warckut commented on src/index.js
> +    requestPage('activity')
Если это был сервер на nginx, где можно было бы задать, чтобы все пути начиная с домена обрабатывались одним файлом, то это было просто сделать, но deploy на github pages. Мне приходит на ум на 404 странице делать редирект на главную страницу с query params. Есть ли какое-то более изящное решение?

2024-07-05 21:05 UTC, tvivls requested changes
молодец
как исправить, тегни меня тут)

2024-07-05 21:05 UTC, tvivls commented on images/marker.svg
не используешь

2024-07-05 21:05 UTC, tvivls commented on 404.html
почти. Только при обновлении кидает на страницу activity. можем сделать так, чтобы роут не изменялся (при обновлении map, оставаться на map; при обновлении timer, оставаться на timer)?

2024-07-05 21:05 UTC, tvivls commented on index.html
> +              <a href="#" class="nav-link">
у всех иконок справа можно убрать href. они никуда не ведут, но при этом добавляют # в url

<img width="400" alt="image" src="https://github.com/Warckut/bee-test/assets/86954004/c140bbcb-01bd-46cc-83fa-f96a4577ab70">

2024-07-05 21:05 UTC, tvivls commented on src/index.js
> +  let view = routes[location.pathname];
почему let?

2024-07-05 21:05 UTC, tvivls commented on src/pages/activity/index.html
> +            <a href="#" class="d-block comment__author mb-3 text-decoration-none text-c_black">
зачем тут ссылка?
ниже везде тоже

2024-07-05 21:05 UTC, tvivls commented on src/pages/map/index.js
> +  var placemark = new YMaps.Placemark(new YMaps.GeoPoint(...PLACE));
var 💀

2024-07-05 21:05 UTC, tvivls commented on src/pages/time/index.js
> +  const result = [hours, minutes, seconds].map((v) => String(v).padStart(2, '0'));
отлично
но пиши делай более понятные названия для переменных
в этом случае `v` ни о чем не говорит.

2024-07-05 21:05 UTC, tvivls commented on images/small-dropdown.svg
можно развернуть images/dropdown.svg с помощью css

2024-07-05 21:05 UTC, tvivls commented on src/index.js
> +function changeActiveTabe(prev, next) {
не изменяется активный таб при нажатии на стрелки Вперед/Назад в браузере

<img width="557" alt="image" src="https://github.com/Warckut/bee-test/assets/86954004/bac87181-b2a7-4a41-95e0-a7e97f6c119d">

2024-07-05 21:05 UTC, tvivls commented on src/index.js
> +function changeActiveTabe(prev, next) {
```suggestion
function changeActiveTab(prev, next) {
```

2024-07-05 21:05 UTC, tvivls commented on src/index.js
> +  }
почему делаешь это тут, а не в самом таймере?

2024-07-05 21:11 UTC, Warckut commented on src/index.js
> +  }
А как таймер изнутри может узнать, что ему надо прекращать работать?

2024-07-05 21:13 UTC, Warckut commented on 404.html
Можно маленькую подсказку как это сделать?

2024-07-05 21:20 UTC, tvivls commented on src/index.js
> +  }
аналогичным образом, с использованием текущего url. Ты можешь достать url из любого файла

2024-07-05 21:36 UTC, tvivls commented on 404.html
при первом открытии сайта, по сути у тебя открывается index.html + нужный контент. А при обновлении страницы, у тебя открывается 404.html. Соответственно нужно сделать так, чтобы 404.html работала точно так же, как index.html

2024-07-06 10:18 UTC, Warckut commented on images/small-dropdown.svg
В принципе я так и делаю, просто дело в том что есть две стрелочки - маленькая и большая. На макете маленькая везде поднята вверх, а большая везде опущена вниз. И чтобы для обоих svg работало свойство:
.menu .dropdown-row.up {
  transform: rotate(180deg);
}
одну из них я перевернул на 180 в svg файле
Написать для двух видов галочек разные css?

2024-07-08 08:14 UTC, Warckut commented
@tvivls, замечания исправлены

2024-07-08 12:04 UTC, IvanKoigerov commented on src/variables.css
> +}
такие себе название black blue white

Мы выносим цвета для двух вещей, чтобы проще было писать код и понимать что это такое. А также для того, чтобы если дизайнер изменит цветовую палитру тоооо мы бы могла быстро изменить цвета в переменных и использовать.

А так как у тебя в имени есть цвет, то все не будет так гладко работать, потому что тебе придется переменные переименовывать и вручную везде менять цвет

2024-07-08 12:04 UTC, IvanKoigerov commented on src/index.css
> +}
Не корректно стилизовать то место где ты отображаешь страницу, для той или иной страницы цвета могут быть разные и текст и размер, поэтому лучше всего это делать в родительском диве для каждой страницы отдельно.

2024-07-08 12:04 UTC, IvanKoigerov commented on src/index.js
> +window.START_TIME = new Date().getTime();
Не очень хорошая идея закидывать переменные в window
Из-за этого у тебя может начаться хаус. Будет 20 переменных в window, и это будет оч плохо

А также в такой ситуации оч легко в window накидать различных вещей со стороны пользователя, что оч легко сломало бы твое приложение

2024-07-08 12:04 UTC, IvanKoigerov commented on src/index.js
> +  const view = routes[location.pathname];
view ни о чем не говорящие имя переменной

2024-07-09 08:17 UTC, Warckut commented
@IvanKoigerov, исправил

2024-07-09 12:04 UTC, tvivls approved these changes

2024-07-09 12:06 UTC, merged